# Copyright Henok M.

version: '3'
services:
  odoo:
    image: odoo:17.0
    depends_on:
      - postgres
    ports:
      - "8066:8069"
    volumes:
      - data:/var/lib/odoo
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
  postgres:
    image: postgres:16
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  data:
  db: